name: cd test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  # workflow_dispatch

# permissions:
#   contents: read

jobs:
  job_1_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout files
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: pytest
      - name: SSH Remote Command
        uses: appleboy/ssh-action@v0.1.6
        with:
          key: ${{secrets.SSH_KEY}}
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          run: |
            cd /home/cd
            git pull
            cd
            systemctl restart cd

  job_2_goodbye:
    needs: job_1_test
    runs-on: ubuntu-latest
    # if: always()      altijd uitvoeren ook als de eerste job niet slaagt.

    steps:
      - name: Goodbye
        run: echo "Misschien is de website niet up-to-date maar je code is in ieder geval oké !"
        shell: bash

  job_3_superlinter:
    runs-on: ubuntu-latest
    steps:
      - name: checkout files
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: superlint-check
        uses: github/super-linter@v4
